Controllers/authorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u22565991_HW03.Models;

namespace u22565991_HW03.Controllers
{
    public class authorsController : Controller
    {
        private LibraryEntities1 db = new LibraryEntities1();

        // GET: authors
        public async Task<ActionResult> Index()
        {
            return View(await db.authors.ToListAsync());
        }

        // GET: authors/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // GET: authors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: authors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "authorId,name,surname")] authors authors)
        {
            if (ModelState.IsValid)
            {
                db.authors.Add(authors);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(authors);
        }

        // GET: authors/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // POST: authors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "authorId,name,surname")] authors authors)
        {
            if (ModelState.IsValid)
            {
                db.Entry(authors).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(authors);
        }

        // GET: authors/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            authors authors = await db.authors.FindAsync(id);
            if (authors == null)
            {
                return HttpNotFound();
            }
            return View(authors);
        }

        // POST: authors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            authors authors = await db.authors.FindAsync(id);
            db.authors.Remove(authors);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/booksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u22565991_HW03.Models;

namespace u22565991_HW03.Controllers
{
    public class booksController : Controller
    {
        private LibraryEntities1 db = new LibraryEntities1();

        // GET: books
        public async Task<ActionResult> Index()
        {
            var books = db.books.Include(b => b.authors).Include(b => b.types);
            return View(await books.ToListAsync());
        }

        // GET: books/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // GET: books/Create
        public ActionResult Create()
        {
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name");
            ViewBag.typeId = new SelectList(db.types, "typeId", "name");
            return View();
        }

        // POST: books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.books.Add(books);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // POST: books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "bookId,name,pagecount,point,authorId,typeId")] books books)
        {
            if (ModelState.IsValid)
            {
                db.Entry(books).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.authorId = new SelectList(db.authors, "authorId", "name", books.authorId);
            ViewBag.typeId = new SelectList(db.types, "typeId", "name", books.typeId);
            return View(books);
        }

        // GET: books/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            books books = await db.books.FindAsync(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            books books = await db.books.FindAsync(id);
            db.books.Remove(books);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/borrowsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u22565991_HW03.Models;

namespace u22565991_HW03.Controllers
{
    public class borrowsController : Controller
    {
        private LibraryEntities1 db = new LibraryEntities1();

        // GET: borrows
        public async Task<ActionResult> Index()
        {
            var borrows = db.borrows.Include(b => b.books).Include(b => b.students);
            return View(await borrows.ToListAsync());
        }

        // GET: borrows/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            return View(borrows);
        }

        // GET: borrows/Create
        public ActionResult Create()
        {
            ViewBag.bookId = new SelectList(db.books, "bookId", "name");
            ViewBag.studentId = new SelectList(db.students, "studentId", "name");
            return View();
        }

        // POST: borrows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "borrowId,studentId,bookId,takenDate,broughtDate")] borrows borrows)
        {
            if (ModelState.IsValid)
            {
                db.borrows.Add(borrows);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // GET: borrows/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // POST: borrows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "borrowId,studentId,bookId,takenDate,broughtDate")] borrows borrows)
        {
            if (ModelState.IsValid)
            {
                db.Entry(borrows).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.bookId = new SelectList(db.books, "bookId", "name", borrows.bookId);
            ViewBag.studentId = new SelectList(db.students, "studentId", "name", borrows.studentId);
            return View(borrows);
        }

        // GET: borrows/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            borrows borrows = await db.borrows.FindAsync(id);
            if (borrows == null)
            {
                return HttpNotFound();
            }
            return View(borrows);
        }

        // POST: borrows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            borrows borrows = await db.borrows.FindAsync(id);
            db.borrows.Remove(borrows);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/typesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using u22565991_HW03.Models;

namespace u22565991_HW03.Controllers
{
    public class typesController : Controller
    {
        private LibraryEntities1 db = new LibraryEntities1();

        // GET: types
        public async Task<ActionResult> Index()
        {
            return View(await db.types.ToListAsync());
        }

        // GET: types/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = await db.types.FindAsync(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // GET: types/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: types/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "typeId,name")] types types)
        {
            if (ModelState.IsValid)
            {
                db.types.Add(types);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(types);
        }

        // GET: types/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = await db.types.FindAsync(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // POST: types/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "typeId,name")] types types)
        {
            if (ModelState.IsValid)
            {
                db.Entry(types).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(types);
        }

        // GET: types/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            types types = await db.types.FindAsync(id);
            if (types == null)
            {
                return HttpNotFound();
            }
            return View(types);
        }

        // POST: types/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            types types = await db.types.FindAsync(id);
            db.types.Remove(types);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/Home.cshtml
@model u22565991_HW03.Models.CombinedViewModel
@using PagedList.Mvc;

<style>
    body {
        margin: 0;
        padding-top: 120px;
        padding-bottom: 20px;
    }
    .navbar {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        background-color: #012347;
        height: 100px;
        z-index: 100;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    }

        .navbar .icon {
            float: left;
            margin: 10px 20px;
            color: #fff;
            font-size: 50px;
        }

        .navbar .brand {
            float: left;
            margin: 24px 0;
            margin-right: 50px;
            color: #fff;
            font-size: 40px;
        }

    .nav-links {
        float: right;
        margin: 30px 70px;
        font-size: 20px;
        margin-top: 40px;
    }

        .nav-links a {
            color: #fff;
            text-decoration: none;
            margin-left: 30px;
        }

    .container {
        display: flex;
        gap: 20px;
        margin-left: 0;
    }

        .container > div {
            flex: 1;
            padding: 10px;
            margin: 10px;
        }

    table {
        border-collapse: collapse;
        width: 100%; 
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 22px; 
    }

    th {
        background-color: #f2f2f2;
    }

    .btn {
        display: inline-block;
        font-weight: 400;
        color: #212529;
        text-align: center;
        vertical-align: middle;
        user-select: none;
        background-color: #007bff;
        border: 1px solid transparent;
        padding: 10px; 
        font-size: 1.5rem;
        line-height: 1.5;
        border-radius: .25rem;
        margin-bottom: 20px;
        margin-left: 500px;
        color: #fff;
    }

        .btn:hover {
            background-color: #0056b3;
        }

    .pagination {
        margin-top: 20px; 
    }

        .pagination a {
            padding: 8px 16px;
            text-decoration: none;
            color: #007bff;
            border: 1px solid #007bff;
            margin: 0 6px; 
        }

            .pagination a.active {
                background-color: #007bff;
                color: #fff;
            }
</style>
<body>
    <div class="container">
        <div>
            <h2>Students</h2>
            @Html.ActionLink("Create", "Create", "students", null, new { @class = "btn btn-primary" })
            <table>
                <tr>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>Birth Date</th>
                    <th>Gender</th>
                    <th>Class</th>
                    <th>Point</th>
                </tr>
                @foreach (var item in Model.Students)
                {
                    <tr>
                        <td>@item.name</td>
                        <td>@item.surname</td>
                        <td>@item.birthdate</td>
                        <td>@item.gender</td>
                        <td>@(item.@class)</td>
                        <td>@item.point</td>
                    </tr>
                }
            </table>
            <div class="pagination">
                Page @(Model.Students.PageCount < Model.Students.PageNumber ? 0 : Model.Students.PageNumber) of @Model.Students.PageCount
                @if (Model.Students.HasPreviousPage)
                {
                    @Html.ActionLink("<<", "Home", new { page = 1 })
                    @Html.Raw(" ");
                    @Html.ActionLink("< Prev", "Home", new { page = Model.Students.PageNumber - 1 })
                }
                @if (Model.Students.HasNextPage)
                {
                    @Html.ActionLink("Next >", "Home", new { page = Model.Students.PageNumber + 1 })
                    @Html.Raw(" ");
                    @Html.ActionLink(">>", "Home", new { page = Model.Students.PageCount })
                }
            </div>
        </div>

        <div>
            <h2>Books</h2>
            @Html.ActionLink("Create", "Create", "books", null, new { @class = "btn btn-primary" })
            <table>
                <tr>
                    <th>Name</th>
                    <th>Page Count</th>
                    <th>Point</th>
                    <th>Authour ID</th>
                    <th>Type ID</th>
                    <th>Status</th>
                </tr>
                @for (int i = 0; i < Model.Books.Count(); i++)
                {
                    var book = Model.Books.ElementAt(i);
                    var borrow = Model.Borrows.ElementAt(i);
                    <tr>
                        <td>@book.name</td>
                        <td>@book.pagecount</td>
                        <td>@book.point</td>
                        <td>@book.authorId</td>
                        <td>@book.typeId</td>
                        <td>
                            @if (borrow.broughtDate != null)
                            {
                                <text>Available</text>
                            }
                            else
                            {
                                <text>Out</text>
                            }
                        </td>
                    </tr>
                }
            </table>

            <div class="pagination">
                Page @(Model.Books.PageCount < Model.Books.PageNumber ? 0 : Model.Books.PageNumber) of @Model.Books.PageCount
                @if (Model.Books.HasPreviousPage)
                {
                    @Html.ActionLink("<<", "Home", new { page = 1 })
                    @Html.Raw(" ");
                    @Html.ActionLink("< Prev", "Home", new { page = Model.Books.PageNumber - 1 })
                }
                @if (Model.Books.HasNextPage)
                {
                    @Html.ActionLink("Next >", "Home", new { page = Model.Books.PageNumber + 1 })
                    @Html.Raw(" ");
                    @Html.ActionLink(">>", "Home", new { page = Model.Books.PageCount })
                }
            </div>
        </div>
    </div>
</body>

Views/Home/Maintain.cshtml
@model u22565991_HW03.Models.CombinedViewModel
@using PagedList.Mvc;

<style>
    body {
        margin: 0;
        padding-top: 120px;
        padding-bottom: 20px;
    }

    .navbar {
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        background-color: #012347;
        height: 100px;
        z-index: 100;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1);
    }

        .navbar .icon {
            float: left;
            margin: 10px 20px;
            color: #fff;
            font-size: 50px;
        }

        .navbar .brand {
            float: left;
            margin: 24px 0;
            margin-right: 50px;
            color: #fff;
            font-size: 40px;
        }

    .nav-links {
        float: right;
        margin: 30px 70px;
        font-size: 20px;
        margin-top: 40px;
    }

        .nav-links a {
            color: #fff;
            text-decoration: none;
            margin-left: 30px;
        }

    .container {
        display: flex;
        gap: 20px;
        margin-left: -50px;
    }

        .container > div {
            flex: 1;
            padding: 10px;           
            margin: 10px;
        }

    table {
        border-collapse: collapse;
        width: 100%;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 18px;
    }

    th {
        background-color: #f2f2f2;
    }

    h2 {
        margin-bottom: -45px;
    }

    .btn {
        display: inline-block;
        font-weight: 400;
        color: #212529;
        text-align: center;
        vertical-align: middle;
        user-select: none;
        background-color: #007bff;
        border: 1px solid transparent;
        padding: 10px;
        font-size: 1.5rem;
        line-height: 1.5;
        border-radius: .25rem;
        margin-bottom: 20px;
        margin-left: 380px;
        color: #fff;
    }

        .btn:hover {
            background-color: #0056b3;
        }

    .pagination {
        margin-top: 20px;
    }

        .pagination a {
            padding: 8px 16px;
            text-decoration: none;
            color: #007bff;
            border: 1px solid #007bff;
            margin: 0 6px;
        }

            .pagination a.active {
                background-color: #007bff;
                color: #fff;
            }

    .CRUD {
        padding: 24px;
    }
</style>
<body>
    <div class="container">
        <div>
            <h2>Authors</h2>
            @Html.ActionLink("Create", "Create", "authors", null, new { @class = "btn btn-primary" })
            <table>
                <tr>
                    <th>Name</th>
                    <th>Surname</th>
                    <th>CRUD</th>
                </tr>
                @foreach (var item in Model.Authors)
                {
            <tr>
                <td>@item.name</td>
                <td>@item.surname</td>
                <td>
                    <button><a href="@Url.Action("Edit", "authors", new { id = item.authorId })">Update</a></button>
                    <button><a href="@Url.Action("Delete", "authors", new { id = item.authorId })">Delete</a></button>
                    <button><a href="@Url.Action("Create", "authors", new { id = item.authorId })">Create</a></button>
                </td>
            </tr>
                }
            </table>
            <div class="pagination">
                Page @(Model.Authors.PageCount < Model.Authors.PageNumber ? 0 : Model.Authors.PageNumber) of @Model.Authors.PageCount
                @if (Model.Authors.HasPreviousPage)
                {
                    @Html.ActionLink("<<", "Maintain", new { page = 1 })
                    @Html.Raw(" ");
                    @Html.ActionLink("< Prev", "Maintain", new { page = Model.Authors.PageNumber - 1 })
                }
                @if (Model.Authors.HasNextPage)
                {
                    @Html.ActionLink("Next >", "Maintain", new { page = Model.Authors.PageNumber + 1 })
                    @Html.Raw(" ");
                    @Html.ActionLink(">>", "Maintain", new { page = Model.Authors.PageCount })
                }
            </div>
        </div>

        <div>
            <h2>Types</h2>
            @Html.ActionLink("Create", "Create", "types", null, new { @class = "btn btn-primary" })
            <table>
                <tr>
                    <th>Name</th>
                    <th>CRUD</th>
                </tr>
                @foreach (var listItem in Model.Types)
                {
            <tr>
                <td>@listItem.name</td>
                <td>
                    <button><a href="@Url.Action("Edit", "types", new { id = listItem.typeId })">Update</a></button>
                    <button><a href="@Url.Action("Delete", "types", new { id = listItem.typeId })">Delete</a></button>
                    <button><a href="@Url.Action("Create", "types", new { id = listItem.typeId })">Create</a></button>
                </td>
            </tr>
                }
            </table>
            <div class="pagination">
                Page @(Model.Types.PageCount < Model.Types.PageNumber ? 0 : Model.Types.PageNumber) of @Model.Types.PageCount
                @if (Model.Types.HasPreviousPage)
                {
                    @Html.ActionLink("<<", "Maintain", new { page = 1 })
                    @Html.Raw(" ");
                    @Html.ActionLink("< Prev", "Maintain", new { page = Model.Types.PageNumber - 1 })
                }
                @if (Model.Types.HasNextPage)
                {
                    @Html.ActionLink("Next >", "Maintain", new { page = Model.Types.PageNumber + 1 })
                    @Html.Raw(" ");
                    @Html.ActionLink(">>", "Maintain", new { page = Model.Types.PageCount })
                }
            </div>
        </div>
    </div>

    <div>
        <h2>Borrows</h2>
        @Html.ActionLink("Create", "Create", "borrows", null, new { @class = "btn btn-primary" })
        <table>
            <tr>
                <th>Student ID</th>
                <th>Book ID</th>
                <th>Taken Date</th>
                <th>Brought Date</th>
                <th class="CRUD">CRUD</th>
            </tr>
            @foreach (var listItem in Model.Borrows)
            {
        <tr>
            <td>@listItem.studentId</td>
            <td>@listItem.bookId</td>
            <td>@listItem.takenDate</td>
            <td>@listItem.broughtDate</td>
            <td class="CRUD">
                <button><a href="@Url.Action("Edit", "borrows", new { id = listItem.borrowId })">Update</a></button>
                <button><a href="@Url.Action("Delete", "borrows", new { id = listItem.borrowId })">Delete</a></button>
                <button><a href="@Url.Action("Create", "borrows", new { id = listItem.borrowId })">Create</a></button>
            </td>
        </tr>
            }
        </table>
        <div class="pagination">
            Page @(Model.Borrows.PageCount < Model.Borrows.PageNumber ? 0 : Model.Borrows.PageNumber) of @Model.Borrows.PageCount
            @if (Model.Borrows.HasPreviousPage)
            {
                @Html.ActionLink("<<", "Maintain", new { page = 1 })
                @Html.Raw(" ");
                @Html.ActionLink("< Prev", "Maintain", new { page = Model.Borrows.PageNumber - 1 })
            }
            @if (Model.Borrows.HasNextPage)
            {
                @Html.ActionLink("Next >", "Maintain", new { page = Model.Borrows.PageNumber + 1 })
                @Html.Raw(" ");
                @Html.ActionLink(">>", "Maintain", new { page = Model.Borrows.PageCount })
            }
        </div>
    </div>
</body>